### ISSUE TITLE
Zooming the view from Top Left corner

### ISSUE THREAD

**Issue by alikazim** [Xjasz/AndroidZoomableViewGroup#1]
This zooms the listview from top left corner. Can we controll this? this should zoom the view from the mid point of two fingers. in short this should zoom the view at the pinch position not from top left or top right corner

**Comment by Xjasz** [comment]
It will zoom from the midpoint of your pinch

**Comment by alikazim** [comment]
@Xjasz no its not. Maybe you are unclear with my question.
please see this

http://stackoverflow.com/questions/32242187/how-to-zoom-list-item-from-center-of-pinch

**Comment by begiflow** [comment]
metoo
